version: '3.3'

services:
  postgresql:
    restart: always
    container_name: data_base
    image: postgres:latest
    env_file: env/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgresql_db:/var/lib/postgresql/data

  pgAdmin:
    restart: always
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file: env/pga.env
    volumes:
      - postgresql_admin:/var/lib/pgadmin
    links:
      - postgresql
    depends_on:
      - postgresql

  web:
    build: .
    restart: always
    entrypoint: /entrypoint.sh
    command: python /code/manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      - DB_SERVER=${DB_SERVER}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    links:
      - postgresql
    depends_on:
      - postgresql


volumes:
  postgresql_db:
  postgresql_admin:
